com.farao_community.farao.swe.api.exception.SweInternalException#instance-init#