-------------------------------------------------------------------------------
Test set: com.farao_community.farao.swe.api.exception.SweInvalidDataExceptionTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 s - in com.farao_community.farao.swe.api.exception.SweInvalidDataExceptionTest
